owner: naffiq
repo: emdey-uptime

sites:
  - name: Emdey
    url: https://emdey.kz/
  - name: API Emdey
    url: https://api.emdey.kz/
  - name: MIS Emdey
    url: https://mis.emdey.kz/
  - name: Vet Emdey
    url: https://vet.emdey.kz/
  - name: Densaulyk
    url: https://densaulyk.kz/
  - name: MID Dev
    url: https://mid.dev.emdey.kz/
  - name: API Dev
    url: https://api.dev.emdey.kz/

status-website:
  publish: true
  baseUrl: /emdey-uptime
  name: Emdey Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
