owner: naffiq
repo: emdey-uptime

sites:
  - name: MIS Emdey
    url: https://mis.emdey.kz/
  - name: MIS Emdey Dev
    url: https://mis-dev.emdey.kz/
  - name: Vet Emdey
    url: https://vet.emdey.kz/
  - name: Vet Emdey Dev
    url: https://vet-dev.emdey.kz/
  - name: Emdey
    url: https://emdey.kz/
  - name: Densaulyk
    url: https://densaulyk.kz/

status-website:
  # baseUrl: /emdey-uptime
  name: Emdey Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
